# Generated by Django 3.1.1 on 2021-02-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210130_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
